### ISSUE TITLE
Not work front cam and autofocus

### ISSUE THREAD

**Issue by LinerSRT** [SeriniTY320/thl4000_kk_kernel#1]
Front camera work, but image need rotate 180 degrees and fix inverted colors

**Comment by SeriniTY320** [comment]
Now system will boot, but sensors now work. (SENSOR_ID mistmach)

**Comment by SeriniTY320** [comment]
> Much better! Now i can supply the front cam's using one CMRST pin! 
> Cam not is not detecting (write_cmos edited). (I2C send error (fixable) )
> Windows crash my codegen, and network intarfaces not work! Reverted to correct codegen
> Need edit some pins in codegen using linux based os

**Comment by SeriniTY320** [comment]
[kdSetDriver] :[0][1][1][gc5004_mipi_raw][32]
[[kd_sensorlist]]  Sensor found ID = 0x5004

[kdSetDriver] :[0][1][2][gc2355mipi_raw][32]
[kd_sensorlist]]  Sensor found ID = 0x2355
[[kd_sensorlist]] [CAMERA SENSOR] I2C send failed!!
[[GC2355Raw] ] ERROR: GC2355MIPI_read_cmos_sensor 
[[GC2355Raw] ] GC2355MIPIGetSensorID:ffff 
[[kd_sensorlist]]  No Sensor Found
[[kd_sensorlist]] ERROR:adopt_CAMERA_HW_CheckIsAlive(), No imgsensor alive 

[kdSetDriver] :[0][1][2][gc0310mipiyuv][32] (for this cam need edit power supply, not edited cause he is not using in my phone)

Cam's is detecting.  Main cam work, but front have i2c error. I think i need compile new libs for system
